# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NobleGoal' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NobleGoal

    pod 'RxSwift', '~> 5'
    pod 'RxCocoa', '~> 5'
    pod 'Firebase/Analytics'
    pod 'Firebase/Messaging'
  target 'NobleGoalTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NobleGoalUITests' do
    # Pods for testing
  end

end
